name: Update translated date 2
on:
  pull_request:
    branches:
      - i18n-gitlocalize

jobs:
  translation2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Branch name
        run: echo running on branch ${{ github.head_ref }}
