name: Update translated date 2
on:
  pull_request:
    branches:
      - i18n-gitlocalize

jobs:
  translation2:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

